name: ESLint Config

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - 'packages/eslint-config/**'
      - '.github/workflows/eslint-config.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash
    working-directory: packages/eslint-config

jobs:
  static:
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-slim
    timeout-minutes: 10

    steps:
      - name: Check out
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup Node
        uses: ./.github/actions/setup-node
        with:
          working-directory: packages/eslint-config

      - name: Lint
        run: pnpm lint

      - name: Compiler check
        run: pnpm check:ts
